#!/bin/bash
# =============================================================================
# 02-setup-iscsi-targets.sh
# =============================================================================
# Installs and configures tgt (Linux SCSI target framework) to serve iSCSI
# disk images to worker nodes.
#
# Prerequisites:
#   - Run as root on knode1 (10.200.0.101)
#   - Images created by 01-extract-ubuntu-images.sh in /srv/iscsi/
# =============================================================================

set -e

# Configuration
WORK_DIR="/srv/iscsi"
NODES=("knode2" "knode3" "knode4")
TARGET_IPS=("10.200.0.102" "10.200.0.103" "10.200.0.104")

# -----------------------------------------------------------------------------
# Helper functions
# -----------------------------------------------------------------------------
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

error_exit() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >&2
    exit 1
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
log "Starting iSCSI target setup"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    error_exit "This script must be run as root"
fi

# Verify images exist
log "Verifying disk images..."
for NODE in "${NODES[@]}"; do
    IMG_FILE="$WORK_DIR/${NODE}.img"
    if [[ ! -f "$IMG_FILE" ]]; then
        error_exit "Image not found: $IMG_FILE. Run 01-extract-ubuntu-images.sh first."
    fi
    log "  Found: $IMG_FILE ($(du -h "$IMG_FILE" | cut -f1))"
done

# Install tgt
log "Installing tgt (iSCSI target)..."
apt update
apt install -y tgt

# Create tgt configuration directory
mkdir -p /etc/tgt/conf.d

# Generate tgt configuration
log "Creating tgt configuration..."
cat > /etc/tgt/conf.d/rpi-cluster.conf << EOF
# RPi Cluster iSCSI Targets
# Generated by 02-setup-iscsi-targets.sh

EOF

# Add each target
for i in "${!NODES[@]}"; do
    NODE="${NODES[$i]}"
    TARGET_IP="${TARGET_IPS[$i]}"
    IMG_FILE="$WORK_DIR/${NODE}.img"
    
    cat >> /etc/tgt/conf.d/rpi-cluster.conf << TARGETEOF
<target iqn.2025-05.litaninja.dev:${NODE}>
    backing-store $IMG_FILE
    initiator-address $TARGET_IP
    incominguser iscsi-user iscsi-pass
    # Allow R/W access
    write-cache on
    # Disable header digest (simpler setup)
    header_digest none
    # Worker node connection info
    initiator-name iqn.2025-05.litaninja.dev:initiator-${NODE}
</target>

TARGETEOF
    log "  Configured target for $NODE ($TARGET_IP)"
done

# Stop tgt if running, restart with new config
log "Restarting tgt service..."
systemctl stop tgt || true
systemctl start tgt
systemctl enable tgt

# Wait for tgt to initialize
sleep 2

# Verify targets are configured
log "Verifying iSCSI targets..."
tgtadm --mode target --op show

# Check if targets are listening
log "Checking tgt status..."
systemctl status tgt --no-pager || true

log ""
log "iSCSI target setup complete!"
log ""
log "Next step: Run 03-setup-tftp-server.sh"
log ""
log "To manually check targets: tgt-admin --show"
