# The devcontainer should use the developer target and run as root with podman
# or docker with user namespaces.
FROM ghcr.io/diamondlightsource/ubuntu-devcontainer:noble AS developer

# Add system dependencies for ansible and cluster management
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    apache2-utils \
    dnsutils \
    gh \
    gnupg \
    apt-transport-https \
    ca-certificates

# If the folder `/etc/apt/keyrings` does not exist, it should be created before the curl command
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# allow unprivileged APT programs to read this keyring
chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# This overwrites any existing configuration in /etc/apt/sources.list.d/kubernetes.list
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

# helps tools such as command-not-found to work correctly
chmod 644 /etc/apt/sources.list.d/kubernetes.list

# Add system dependencies for ansible and cluster management
RUN apt-get install -y kubectl \
    && rm -rf /var/lib/apt/lists/*

# get the claude cli as its slightly more up to date than the vscode extension
curl -fsSL https://claude.ai/install.sh | bash

# get the opencode cli 
curl -fsSL https://opencode.ai/install | bash

env PATH=~/.local/bin:$PATH"
